package stateApp.enums;

public enum NetState {
	START_APPLICATION,
    FAULT_CONNECT_SERVER,

	AUTH_FORM_TRY_CONNECTING,
    AUTH_FORM_CONNECTING,
	AUTH_FORM_FAULT_CONNECTING,
	AUTH_FORM_DISCONNECTING,
    AUTH_FORM_AUTHORIZATION_IS_UNKNOW,
    AUTH_FORM_AUTHORIZATION_IS_NOT_OK,

    REG_FORM_REGISTERING,
    REG_FORM_BACK_TO_AUTH,
	REG_FORM_REG_IS_NOT_OK,
	REG_FORM_LOGIN_IS_BUSY,



    MAIN_FORM_AUTHORIZATION_IS_OK
}
